
- hosts: all
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest


  - name: Install unzip
    yum:
      name: unzip
      state: latest


  - name: Unarchive a file that needs to be downloaded
    ansible.builtin.unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page279/icream.zip
      dest: /tmp
      remote_src: yes


  - name: Ansible copy file to remote server
    copy:
      src: /tmp/ice-cream-shop-website-template/
      dest: /var/www/html/
      remote_src: yes

  - name: Start httpd
    service:
      name: httpd
      state: started
      enabled: yes

